# Generated by Django 3.0.8 on 2020-08-03 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
