# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20200803_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
