# Generated by Django 3.1 on 2020-08-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_modeladmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_image',
            new_name='pictures_image',
        ),
    ]
